//
// Created by masno on 3/11/2023.
//

#ifndef ALGORITHMS_AND_DATA_STRUCTURESPZ9_MAIN_H
#define ALGORITHMS_AND_DATA_STRUCTURESPZ9_MAIN_H


class main {

};


#endif //ALGORITHMS_AND_DATA_STRUCTURESPZ9_MAIN_H
